spring:
  datasource:
    url: jdbc:h2:mem:beneficiarydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: beneficiary-service
server:
  port: 8081

