spring:
  application:
    name: beneficiary-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:h2:mem:beneficiarydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# --- Configuration Springdoc OpenAPI Pour problème SWAGGER UI---
springdoc:
  packages-to-scan: com.example.beneficiary-service.web.BeneficiaryRestController
  show-actuator: false
  show-spring-data-rest: false